config/routes.rb
Rails.application.routes.draw do

  root to: 'monsters#index'

  get "favourites", to: "favourites#index"
  get "favourites/fetch", to: "favourites#fetch"

  get 'kickstarter', to: redirect('https://www.kickstarter.com/projects/cawlin/monster-cards-dnd-5e-reference-cards-for-creature-stats?ref=6p8txq')

  resources :quirks, only: [:index, :create]

  get ":page", to: "pages#show"

  resources :monster_sets, only: [:show], path: '' do
    get '/license', to: 'monster_sets#show'
    resources :monsters, only: [:index, :show], path: ''
  end

  get '*unmatched_route', to: 'application#not_found'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :monster_abilities
  belongs_to :monster_set
  serialize :skills, Hash
  serialize :saving_throws, Hash

  CR_XP = {
    "0" => 10,
    "1/8" => 25,
    "1/4" => 50,
    "1/2" => 100,
    "1" => 200,
    "2" => 450,
    "3" => 700,
    "4" => 1100,
    "5" => 1800,
    "6" => 2300,
    "7" => 2900,
    "8" => 3900,
    "9" => 5000,
    "10" => 5900,
    "11" => 7200,
    "12" => 8400,
    "13" => 10000,
    "14" => 11500,
    "15" => 13000,
    "16" => 15000,
    "17" => 18000,
    "18" => 20000,
    "19" => 22000,
    "20" => 25000,
    "21" => 33000,
    "22" => 41000,
    "23" => 50000,
    "24" => 62000,
    "25" => 75000,
    "26" => 90000,
    "27" => 105000,
    "28" => 120000,
    "29" => 135000,
    "30" => 155000
  }

  # calculate the ability modifier for a given ability scote
  #
  # :param score: (int) the score for the abillity in question
  #
  # :return: the modifier for that score
  def ability_mod(score)
    return ((score - 10) / 2).floor
  end

  def to_param
    self.slug
  end
end

app/models/monster_ability.rb
class MonsterAbility < ApplicationRecord
  belongs_to :monster
end

app/models/monster_set.rb
class MonsterSet < ApplicationRecord
  has_many :monsters

  def to_param
    self.slug
  end
end

app/models/quirk.rb
class Quirk < ApplicationRecord
  belongs_to :quirk_category
end

app/models/quirk_category.rb
class QuirkCategory < ApplicationRecord
  has_many :quirks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_monster_set, :reroute_dnd

  def not_found
    render file: "public/404.html", status: :not_found
  end

  def set_monster_set
    @monster_set = MonsterSet.first
  end

  # For legacy /d&d5esrd urls
  def reroute_dnd
    params[:monster_set_id] = '5esrd' if params[:monster_set_id] == 'd&d5esrd'
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    render action: request.path[1..-1]
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
  end

end

app/controllers/monster_sets_controller.rb
class MonsterSetsController < ApplicationController

  # License page
  #
  # @url /:monster_set_slug/license
  #
  def show
    @monster_set = MonsterSet.
      find_by(slug: params[:monster_set_id])
    @title = "#{@monster_set.system} License"
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

  def index
    @title = "Monsters - 5e SRD"
    @monsters = Monster.
      where(monster_set_id: @monster_set.id).
      order(:xp, :name)
  end

  def show
    @monster = Monster.
      includes(:monster_abilities).
      find_by(slug: params[:id])
    if @monster.nil?
      render file: "public/404.html", status: :not_found
    else
      @title = "#{@monster.name} - #{@monster_set.system}"
    end
  end

  private
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Load static page
  #
  # @url /:page
  #
  def show
    if valid_page?
      @title = params[:page].titleize
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/quirks_controller.rb
class QuirksController < ApplicationController

  def index
    @category = QuirkCategory.find(
      ActiveRecord::Base.connection.execute(
        "
        SELECT qc.*, COALESCE(counts.C, 0) AS quirk_count
        FROM quirk_categories AS qc
        LEFT OUTER JOIN (
          SELECT quirk_category_id, COUNT(id) AS c
          FROM quirks
          GROUP BY quirk_category_id
        ) AS counts ON qc.id = counts.quirk_category_id
        ORDER BY quirk_count ASC
        LIMIT 25
        ;
        "
      ).field_values('id').sample
    )

    @existing_quirks = Quirk.
      where(quirk_category_id: @category.id).
      order(:created_at)
  end

  def create
    if params[:desc].present?
      Quirk.create!(
        quirk_category_id: params[:quirk_category_id],
        desc: params[:desc]
      )

      flash[:notice] = "Submission saved 👍"
    end

    redirect_to quirks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/monsters_controller_helper.rb
module MonstersControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quirks_helper.rb
module QuirksHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/favourites/_empty_state.html.erb
<div class="ph2 mb0" id="favourites-empty-state">
  <div class="measure center">
    <span class="db link ph2 pv3 ba bw2 b--black bg-white br3 fw6 shadow-2 tc">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" height="64" width="64" fill="#999" aria-label="Favourite Button">
      	<title>Favourites Button</title>
      	<path d="M259.3 17.8L194 150.2 47.9 171.4c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.1 23 46 46.4 33.7L288 439.6l130.7 68.7c23.3 12.3 50.9-7.5 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8C305-5.9 271.1-6 259.3 17.8zM256.1 160h64c4.7 0 8.4 4.1 8 8.6l-8 112c-.3 4.2-3.8 7.4-8 7.4h-48c-4.2 0-7.7-3.2-8-7.4l-8-112c-.5-4.7 3.5-8.6 8-8.6zM288 392c-22.1 0-40-17.9-40-40s17.9-40 40-40 40 17.9 40 40-17.9 40-40 40z"/>
      </svg>
      <h2 class="ma0 f3 lh-title">You Have No Favourites</h2>
      <p>Add monsters to your favourites with stars <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="10" height="10" viewBox="0 0 13 14" class="icon-favourite" fill="#FFB700">
      <path d="M13 5.055q0 0.172-0.203 0.375l-2.836 2.766 0.672 3.906q0.008 0.055 0.008 0.156 0 0.164-0.082 0.277t-0.238 0.113q-0.148 0-0.312-0.094l-3.508-1.844-3.508 1.844q-0.172 0.094-0.312 0.094-0.164 0-0.246-0.113t-0.082-0.277q0-0.047 0.016-0.156l0.672-3.906-2.844-2.766q-0.195-0.211-0.195-0.375 0-0.289 0.438-0.359l3.922-0.57 1.758-3.555q0.148-0.32 0.383-0.32t0.383 0.32l1.758 3.555 3.922 0.57q0.438 0.070 0.438 0.359z"></path></svg><br>We'll save your list for next time you visit.</p>
      <p><a href="/" class="black hover-bg-washed-yellow">&#8249; Back to <%= @monster_set.system %> Monsters</a></p>
    </span>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96752197-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @title || "Monster Cards" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'application/favicon' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/google_analytics' if ENV['HEROKU_APP_NAME'].present? && ENV['HEROKU_APP_NAME'] == 'monstercards-prod'%>
  </head>

  <body class="bg-washed-green avenir">
  <a href="#main-content" class="clip">Skip to Main Content</a>

    <%= render 'shared/navigation' %>

    <%= yield %>
    
    <%= render 'shared/navigation_modal' %>
  </body>
</html>

app/views/monster_sets/show.html.erb
<article id="main-content" class="mh0-ns mh2 mb2 mt5">
  <div class="pt4-ns pb3-ns ph4-ns pa3 pb1 center measure ba bw2 b--black br3 bg-white shadow-2 lh-copy">
  <h2 class="mv0 f2 lh-title"><%= @monster_set.license %></h2>
  <div><%= simple_format(@monster_set.license_text) %></div>
</article>

app/views/monsters/_empty.html.erb
<div class="ph2 mb0 <%= empty ? '' : 'dn' %>" id="monster-list-empty">
  <div class="measure center">
    <span class="db link ph2 pv3 ba bw2 b--black bg-white br3 fw6 shadow-2 tc">
      <img src='https://microicon-clone.vercel.app/skull/555555/40' class="white" aria-hidden="true" />
      <h2 class="ma0 f3 lh-title mid-gray">No Results</h2>
    </span>
  </div>
</div>

app/views/monsters/index.html.erb
<%= content_for :search_bar do  %>
  <%= render 'shared/search_bar' %>
<% end %>

<%= content_for :filter_menu do  %>
  <%= render 'shared/filter_menu' %>
<% end %>

<article id="monster-list" class="pt5 mt5">
  <%= render 'empty', empty: @monsters.empty? %>
  <%= render 'shared/monsters', monsters: @monsters %>
  <p class="measure center tc">
    <%= link_to 'License', monster_set_license_path(MonsterSet.first), class: 'black hover-bg-washed-yellow' %>
  </p>
</article>

<script>
  $(document).ready(function() {
    favourites.init({set:"<%=@monster_set.slug.html_safe%>"});
    filters.init({
      showSlider: true,
      crXp: <%= Monster::CR_XP.to_json.html_safe %>,
    });
  });
</script>

app/views/monsters/show.html.erb
<article id="main-content" class="mh0-ns mh2 mb2 mt5">
  <div class="pt4-ns pb3-ns ph4-ns pa3 pb1 center measure ba bw2 b--black br3 bg-white shadow-2 relative">

    <a href="javascript:" data-monster-set="<%= @monster_set.slug %>" data-monster="<%= @monster.slug %>" class="favourite-toggle absolute pa2 top-0 right-0 top-1-ns right-1-ns v-mid" role="button">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 13 14" class="icon-favourite">
        <path d="M13 5.055q0 0.172-0.203 0.375l-2.836 2.766 0.672 3.906q0.008 0.055 0.008 0.156 0 0.164-0.082 0.277t-0.238 0.113q-0.148 0-0.312-0.094l-3.508-1.844-3.508 1.844q-0.172 0.094-0.312 0.094-0.164 0-0.246-0.113t-0.082-0.277q0-0.047 0.016-0.156l0.672-3.906-2.844-2.766q-0.195-0.211-0.195-0.375 0-0.289 0.438-0.359l3.922-0.57 1.758-3.555q0.148-0.32 0.383-0.32t0.383 0.32l1.758 3.555 3.922 0.57q0.438 0.070 0.438 0.359z"></path>
      </svg>      
      <span class="clip">Add <%= @monster.name %> to Favourites</span>
    </a>

    <h2 class="mv0 f2-ns f3 lh-title"><%= @monster.name %></h2>
    <p class="i mt0 lh-copy ">
      <span class="b">Challenge <%= @monster.cr %> (<%= number_with_delimiter(@monster.xp, :delimiter => ',')%> XP)</span>,
      <%= "#{@monster.size} #{@monster.monster_type}" %>
      <%= " (#{@monster.subtype})" if @monster.subtype?%>
      <%=", #{@monster.alignment}" %>
    </p>

    <section class="bt bw2">
      <p class="f4-ns lh-copy">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" width="16" height="16"><path d="M414.9 24C361.8 24 312 65.7 288 89.3 264 65.7 214.2 24 161.1 24 70.3 24 16 76.9 16 165.5c0 72.6 66.8 133.3 69.2 135.4l187 180.8c8.8 8.5 22.8 8.5 31.6 0l186.7-180.2c2.7-2.7 69.5-63.5 69.5-136C560 76.9 505.7 24 414.9 24z" style="fill: #FF4136;"/></svg> <abbr title="Hit Points" class="b">HP</abbr> <%= "#{@monster.hp} (#{@monster.hit_dice})" %>
        
      <span class="ph2">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="16" height="16"><path d="M466.5 83.7l-192-80a48.15 48.15 0 0 0-36.9 0l-192 80C27.7 91.1 16 108.6 16 128c0 198.5 114.5 335.7 221.5 380.3 11.8 4.9 25.1 4.9 36.9 0C360.1 472.6 496 349.3 496 128c0-19.4-11.7-36.9-29.5-44.3z" style="fill: #19A974;" /></svg>
        <abbr title="Armor Class" class="b">AC</abbr> <%= @monster.ac %>
      </span>

      <span class="dib">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="16" height="16"><path d="M256 8c137 0 248 111 248 248S393 504 256 504 8 393 8 256 119 8 256 8zm-28.9 143.6l75.5 72.4H120c-13.3 0-24 10.7-24 24v16c0 13.3 10.7 24 24 24h182.6l-75.5 72.4c-9.7 9.3-9.9 24.8-.4 34.3l11 10.9c9.4 9.4 24.6 9.4 33.9 0L404.3 273c9.4-9.4 9.4-24.6 0-33.9L271.6 106.3c-9.4-9.4-24.6-9.4-33.9 0l-11 10.9c-9.5 9.6-9.3 25.1.4 34.4z" style="fill: #408BC9;"/></svg>
        <abbr title="Speed" class="b">SPD</abbr> <%= @monster.speed %>
      </span>
      </p>
    </section>

    <section class="bt bw2">
      <table class="mv3 w-100 lh-solid">
        <caption class="clip">Ability Scores</caption>
        <tr class="tc f4-ns">
          <th>STR</th>
          <th>DEX</th>
          <th>CON</th>
          <th>INT</th>
          <th>WIS</th>
          <th>CHA</th>
        </tr>
        <tr class="tc tracked-tight">
          <td>
            <small class="gray"><%= @monster.str %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.str)) %>)</strong class="fw5"></td>
          <td><small class="gray"><%= @monster.dex %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.dex)) %>)</strong class="fw5"></td>
          <td><small class="gray"><%= @monster.con %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.con)) %>)</strong class="fw5"></td>
          <td><small class="gray"><%= @monster.int %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.int)) %>)</strong class="fw5"></td>
          <td><small class="gray"><%= @monster.wis %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.wis)) %>)</strong class="fw5"></td>
          <td><small class="gray"><%= @monster.cha %></small> <strong class="fw5">(<%= sprintf("%+d", @monster.ability_mod(@monster.cha)) %>)</strong class="fw5"></td>
        </tr>
      </table>
    </section>

    <section class="bt bw2">
      <dl class="lh-copy">
        <% if @monster.skills.length > 0 %>
          <dt class="fl b mr1">Skills</dt>
          <dd class="ml0">
          <% @monster.skills.each_with_index do |(skill_type, skill_bonus), index| %><%= "#{skill_type.capitalize}: +#{skill_bonus}" %><%= ", " if index < @monster.skills.length-1 %><% end %>
          </dd>
        <% end %>
        <% if @monster.senses? %>
          <dt class="fl b mr1">Senses</dt>
          <dd class="ml0"><%= @monster.senses.capitalize %></dd>
        <% end %>
        <dt class="fl b mr1">Languages</dt>
        <dd class="ml0"><%= @monster.languages != "" ? @monster.languages.capitalize : "None" %></dd>
        <% if @monster.damage_vulnerabilities.length >0  %>
          <dt class="fl b mr1">Damage Vulnerabilities</dt>
          <dd class="ml0"><%= @monster.damage_vulnerabilities %></dd>
        <% end %>
        <% if @monster.damage_resistances.length >0  %>
          <dt class="fl b mr1">Damage Resistances</dt>
          <dd class="ml0"><%= @monster.damage_resistances %></dd>
        <% end %>
        <% if @monster.damage_immunities.length >0  %>
          <dt class="fl b mr1">Damage Immunities</dt>
          <dd class="ml0"><%= @monster.damage_immunities %></dd>
        <% end %>
        <% if @monster.condition_immunities.length >0  %>
          <dt class="fl b mr1">Condition Immunities</dt>
          <dd class="ml0"><%= @monster.condition_immunities %></dd>
        <% end %>
      </dl>
    </section>

    <% if @monster.monster_abilities.where(ability_type: "special").count > 0 %>
      <section class="bt bw2">
        <dl class="lh-copy">
          <% @monster.monster_abilities.where(ability_type: "special").each do |ability| %>
            <dt class="fl b mr1"><%= ability.name %></dt>
            <dd class="ml0 mb3"><%= ability.desc %></dd>
          <% end %>
        </dl>
      </section>
    <% end %>

    <% if @monster.monster_abilities.where(ability_type: "action").count > 0 %>
      <h2 class="mt0 mb2 f3 lh-title pt2">Actions</h2>
      <section class="bt bw2">
        <dl class="lh-copy">
          <% @monster.monster_abilities.where(ability_type: "action").each do |ability| %>
            <dt class="fl b mr1"><%= ability.name %></dt>
            <dd class="ml0 mb3"><%= ability.desc %></dd>
          <% end %>
        </dl>
      </section>
    <% end %>

    <% if @monster.monster_abilities.where(ability_type: "legendary").count > 0 %>
      <h2 class="mt0 mb2 f3 lh-title pt2">Legendary Actions</h2>
      <section class="bt bw2">
        <dl class="lh-copy">
          <% @monster.monster_abilities.where(ability_type: "legendary").each do |ability| %>
            <dt class="fl b mr1"><%= ability.name %></dt>
            <dd class="ml0 mb3"><%= ability.desc %></dd>
          <% end %>
        </dl>
      </section>
    <% end %>

    <% if @monster.monster_abilities.where(ability_type: "reaction").count > 0 %>
      <h2 class="mt0 mb2 f3 lh-title pt2">Reactions</h2>
      <section class="bt bw2">
        <dl class="lh-copy">
          <% @monster.monster_abilities.where(ability_type: "reaction").each do |ability| %>
            <dt class="fl b mr1"><%= ability.name %></dt>
            <dd class="ml0 mb3"><%= ability.desc %></dd>
          <% end %>
        </dl>
      </section>
    <% end %>

    <footer class="bt bw2 lh-copy">
      <p><%= link_to @monster.name, monster_set_monster_path(@monster_set, @monster), class: 'black hover-bg-washed-yellow'%>
      from 
      <a href="/" class="black hover-bg-washed-yellow"><%= @monster_set.system %></a></p>
    </footer>
  </div>
</article>

<article class="br3 ba b--black-10 bg-white mv4 mw5 center absolute-l top-2 right-1 ">
  <img src="<%= asset_path 'evan-and-colin-monster-cards-5e-product.png' %>" alt="" class="db w-100 br2 br--top" >
  <div class="pa2 ph3-ns pb3-ns">
    <div class="dt w-100 mt1">
      <div class="dtc">
        <h1 class="f5 mv0">Buy Physical Monster Cards</h1>
      </div>
    </div>
    <p class="f6 lh-copy measure mt2 mid-gray">
      We made a deck of 70 premium cards with original art and quirks!
    </p>
    <a class="f6 link dim br2 ph3 pv2 mb0 dib white bg-near-black mb1" href="https://evanandcolin.com">Check It Out</a>
  </div>
</article>

<script>
  $(document).ready(function() {
    favourites.init({set:"<%=@monster_set.slug.html_safe%>"});
  });
</script>

app/views/shared/_filter_menu.html.erb
<section class="pv3 ph2 bb bw2 b--black bg-light-red">
  <div class="measure center">
    <div class="bg-white cf">
      <h2 class="clip">Filter by Challenge Rating</h2>
        <div id="cr-filter-slider"></div>
    </div>
  </div>
</section>

app/views/shared/_monster.html.erb
<li class="db measure center relative" style="margin-top:-0.6rem;">
  <%= link_to monster_set_monster_path(@monster_set, monster), class: 'db link black ph2 pv3 hover-bg-washed-yellow ba bw2 b--black bg-white br3 fw6 shadow-2', data: {name: monster.name, xp: monster.xp} do %> <span class="monster-name"><%= monster.name %></span> <small class="fr mr4 pr1 gray">CR <%= monster.cr %></small>
  <% end %>
  
  <span class='hidden monster-xp'>
    <%= monster.xp %>
  </span>

  <a href="javascript:" data-monster-set="<%=@monster_set.slug%>" data-monster="<%=monster.slug%>" class="favourite-toggle absolute pv3 ph3 top-0 right-0" role="button">
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 13 14" class="icon-favourite">
      <path d="M13 5.055q0 0.172-0.203 0.375l-2.836 2.766 0.672 3.906q0.008 0.055 0.008 0.156 0 0.164-0.082 0.277t-0.238 0.113q-0.148 0-0.312-0.094l-3.508-1.844-3.508 1.844q-0.172 0.094-0.312 0.094-0.164 0-0.246-0.113t-0.082-0.277q0-0.047 0.016-0.156l0.672-3.906-2.844-2.766q-0.195-0.211-0.195-0.375 0-0.289 0.438-0.359l3.922-0.57 1.758-3.555q0.148-0.32 0.383-0.32t0.383 0.32l1.758 3.555 3.922 0.57q0.438 0.070 0.438 0.359z"></path>
    </svg>
    <span class="clip">Add <%= monster.name %> to Favourites</span></a>
</li>

app/views/shared/_monsters.html.erb
<% if (params[:controller] == "monsters" && params[:action] == "index") %>
  <ul class="list ph2 pb2 mb0" style="margin-top: 3rem;">
<% else %>
  <ul class="list ph2 pb2 mb0" style="margin-top: 0.5rem;"">
<% end %>
  <% monsters.each do |monster| %>
    <%= render 'shared/monster', monster: monster %>
  <% end %>
</ul>

app/views/shared/_navigation.html.erb
<header class="fixed bg-black top-0 left-0 w-100 shadow-2 z-1">
  <nav class="measure center cf">
    <a class="link white dib fl ph2 pv3 underline-hover" href="/">
      <h1 class="f5 normal ma0">
      <%= @monster_set.system %> Monsters
      </h1>
    </a>
    <a class="link white dib fr ph2 pv3 js-modal underline-hover" href="" data-modal-prefix-class="primary-menu" data-modal-content-id="primary-navigation" data-modal-close-img="https://microicon-clone.vercel.app/x/FF725C/24" id="label_modal_6">Menu</a>
    <%= link_to 'Favourites', favourites_path, class: 'link white dib fr ph2 pv3 underline-hover' %>
  </nav>

  <%= yield :search_bar %>
  <%= yield :filter_menu if (params[:controller] == "monsters" && params[:action] == "index") %>
</header>

app/views/shared/_navigation_modal.html.erb
<div id="primary-navigation" class="dn">
  <div class="measure center pt4-ns pb3-ns ph4-ns pa3 pb1">
  
  <h2 class="mt0 mb2 f3 lh-title pt2">Monster Cards</h2>
  <ul class="list pl0 f4 mt0">
    <li class="lh-copy bb bw1 b--black-20"><a href="/about" class="link light-red pv3 db underline-hover">About</a></li>
    <li class="lh-copy bb bw1 b--black-20"><a href="/change_log" class="link light-red pv3 db underline-hover">Changelog</a></li>
    <li class="lh-copy bb bw1 b--black-20"><a href="https://evanandcolin.com" class="link light-red pv3 db underline-hover">Buy Physical Monster Cards</a></li>
  </ul>

    <h2 class="mt0 mb2 f3 lh-title pt2"><%= @monster_set.system %></h1>
    <ul class="list pl0 f4 mt0">
      <li class="lh-copy bb bw1 b--black-20"><a href="/" class="link light-red pv3 db underline-hover">Monsters</a></li>
      <li class="lh-copy bb bw1 b--black-20"><a href="/favourites" class="link light-red pv3 db underline-hover">Favourites</a></li>
      <li class="lh-copy bb bw1 b--black-20"><%= link_to 'License', monster_set_license_path(MonsterSet.first), class: 'link light-red pv3 db underline-hover' %></li>
    </ul>
  </div>
</div>